# Config file for automatic testing at travis-ci.org

language: python
dist: xenial

install:
  - pip install -U tox

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    # --
    - stage: test
      name: "tests python3.7"
      python: 3.7
      script: tox -e py37
      after_success:
        - pip install codecov
        - codecov --file .dev/.tox/py37/coverage.xml
    - name: "tests python3.6"
      python: 3.6
      script: tox -e py36
    - name: "mypy"
      python: 3.7
      script: tox -e mypy
    - name: "flake8"
      python: 3.7
      script: tox -e flake8
    # --
    - stage: deploy
      python: 3.7
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: thomasjahoda
        password:
          secure: aGa+GjRZQxUlBsp1BcK7cjx5NYQSaGjC1wwmyNyIvY8WP76NS/XEAJXCd1rRGawduFjowB8bWe1w+ardo0yl/4QBRDjwN2AjGRguI2px7tlk2NYsVRbOurbxKhSsRmWzQ0xjYF4WpRMr5vYc+tY49mbVr5guLaQcGFTZj9mUzxxIIfTQhdrB4KxsaiiBGsy8Q3nRspzAXnXMaHWh5lipQFaqd+zp1o41+XcMpXvc0l+fpIVAU4V7l+X11lGGA52UTZLjQ2/kR/JBxdb0jmxVRRveYkHOXLKkx9Aujl4CVcd306R7/d0JarONUKcotyhYcg3VBXl6nVIpGpmhbJxwp/qRG+ZRBf3IxnTuRbAd4ETVHuQjS6uDzEZNvEpjsTITLaPHWrL82o3NS/Npey+skHzmsXPBCYDEB5QuHWSSzQ7pvHhn50ktdPzqlR2AAl7Gl7lbz8oZJLmo3EAT/aYcCT1lXg6j6mpjPHZ0nE8NCxbUcMLt8yK8a5ndsf7T+Rt6LBMwAuma2jDUi6FlqtCwsru4nd9BW0hXM+I/PBJ5ITgi7vjVYncoK4ZY4wN8hM/BfYw/xmCimlLnKw6okWfSj4JOiqf7uyjMCBIVmmEXcSfnAlUmNSejAAxtpT8KC4ts1I7HZHQrHwyekyYvqjgwck5407PO/Q/+x0L6exC9l9s=
        on:
          tags: true
          repo: thomasjahoda/tjpy_subprocess_util
          python: 3.7
